<?php

namespace IUT\PlaningBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DateHeureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateHeureRepository extends EntityRepository
{
}
